!!python/object:pm_icecon.config.models.bt.BootstrapParams
__dict__:
  add1: 0.0
  add2: -2.0
  maxic: 1.0
  maxtb: 320.0
  minic: 10.0
  mintb: 10.0
  v1937_params: !!python/object:pm_icecon.config.models.bt.TbSetParams
    __dict__:
      ice_tie_point_set: !!python/tuple
      - 259.4
      - 261.6
      lnline:
        offset: 62.89
        slope: 0.7618
      water_tie_point_set: !!python/tuple
      - 207.6
      - 182.7
    __fields_set__: !!set
      ice_tie_point_set: null
      lnline: null
      water_tie_point_set: null
    __private_attribute_values__: {}
  vh37_params: !!python/object:pm_icecon.config.models.bt.TbSetParams
    __dict__:
      ice_tie_point_set: !!python/tuple
      - 259.4
      - 247.3
      lnline:
        offset: -90.62
        slope: 1.2759
      water_tie_point_set: !!python/tuple
      - 207.6
      - 131.9
    __fields_set__: !!set
      ice_tie_point_set: null
      lnline: null
      water_tie_point_set: null
    __private_attribute_values__: {}
  weather_filter_seasons:
  - !!python/object:pm_icecon.config.models.bt.WeatherFilterParamsForSeason
    __dict__:
      end_day: null
      end_month: 12
      start_day: null
      start_month: 1
      weather_filter_params: !!python/object:pm_icecon.config.models.bt.WeatherFilterParams
        __dict__:
          wintrc: 85.13
          wslope: 0.5379
          wxlimt: 14.3
        __fields_set__: !!set
          wintrc: null
          wslope: null
          wxlimt: null
        __private_attribute_values__: {}
    __fields_set__: !!set
      end_day: null
      end_month: null
      start_day: null
      start_month: null
      weather_filter_params: null
    __private_attribute_values__: {}
__fields_set__: !!set
  add1: null
  add2: null
  maxic: null
  maxtb: null
  minic: null
  mintb: null
  v1937_params: null
  vh37_params: null
  weather_filter_seasons: null
__private_attribute_values__: {}
