!!python/object:pm_icecon.config.models.bt.BootstrapParams
__dict__:
  add1: 0.0
  add2: -2.0
  maxic: 1.0
  maxtb: 320.0
  minic: 10.0
  mintb: 10.0
  v1937_params: !!python/object:pm_icecon.config.models.bt.TbSetParams
    __dict__:
      ice_tie_point_set: !!python/tuple
      - 255.67
      - 258.341
      lnline:
        offset: 47.0061
        slope: 0.809335
      water_tie_point_set: !!python/tuple
      - 201.916
      - 178.771
    __fields_set__: !!set
      ice_tie_point_set: null
      lnline: null
      water_tie_point_set: null
    __private_attribute_values__: {}
  vh37_params: !!python/object:pm_icecon.config.models.bt.TbSetParams
    __dict__:
      ice_tie_point_set: !!python/tuple
      - 255.67
      - 241.713
      lnline:
        offset: -73.5471
        slope: 1.21104
      water_tie_point_set: !!python/tuple
      - 201.916
      - 132.815
    __fields_set__: !!set
      ice_tie_point_set: null
      lnline: null
      water_tie_point_set: null
    __private_attribute_values__: {}
  weather_filter_seasons:
  - !!python/object:pm_icecon.config.models.bt.WeatherFilterParamsForSeason
    __dict__:
      end_day: 15
      end_month: 10
      start_day: null
      start_month: 6
      weather_filter_params: !!python/object:pm_icecon.config.models.bt.WeatherFilterParams
        __dict__:
          wintrc: 89.2
          wslope: 0.50375
          wxlimt: 21.0
        __fields_set__: !!set
          wintrc: null
          wslope: null
          wxlimt: null
        __private_attribute_values__: {}
    __fields_set__: !!set
      end_day: null
      end_month: null
      start_day: null
      start_month: null
      weather_filter_params: null
    __private_attribute_values__: {}
  - !!python/object:pm_icecon.config.models.bt.WeatherFilterParamsForSeason
    __dict__:
      end_day: null
      end_month: 5
      start_day: 16
      start_month: 10
      weather_filter_params: !!python/object:pm_icecon.config.models.bt.WeatherFilterParams
        __dict__:
          wintrc: 87.6467
          wslope: 0.517333
          wxlimt: 14.0
        __fields_set__: !!set
          wintrc: null
          wslope: null
          wxlimt: null
        __private_attribute_values__: {}
    __fields_set__: !!set
      end_day: null
      end_month: null
      start_day: null
      start_month: null
      weather_filter_params: null
    __private_attribute_values__: {}
__fields_set__: !!set
  add1: null
  add2: null
  maxic: null
  maxtb: null
  minic: null
  mintb: null
  v1937_params: null
  vh37_params: null
  weather_filter_seasons: null
__private_attribute_values__: {}
